# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: CI

on:
  push:
    paths:
      # Trigger only when src/** changes
      - ".github/release.json"
      
  pull_request:
    paths:
    # Trigger only when src/** changes
      - ".github/release.json"

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'  
     
    - name: Read tag_latest
      id: tag_latest
      uses:  ashley-taylor/read-json-property-action@v1.2
      with:
        path: ./.github/release.json
        property: tag_latest
        
 
    - name: Package Jar
      run: |
        # 复制整个文件夹
        mkdir target
        cp -r src/. target

        # 删除不需要的java文件
        rm -rf ./target/nicelee/test

        # 获取java文件列表
        cd target
        find `pwd` -name "*.java" > ../sources.txt
        cd ..

        # 获取环境变量,解压lib包
        cd libs
        find `pwd` -name "*.jar" > ../libs.txt
        cat ../libs.txt
        cd ../target
        for jar in  `cat ../libs.txt`
        do
            jclasspath=$jar:$jclasspath
            echo $jar
            jar xvf $jar
        done
        cd ..
        echo $jclasspath

        # 编译java
        javac -cp $jclasspath -encoding UTF-8 @sources.txt

        # 删除所有.java文件
        cd target
        find . -name "*.java" |xargs rm -rf {}
        cd ..

        # 打包
        jar cvfe ILikeAcFun.jar nicelee.ui.FrameMain -C ./target .

    - name: ZIP files
      run: |
        rm -rf ./config
        rm -rf ./LICENSE
        mkdir ./config/
        mkdir ./LICENSE/
        mv -f ./release/install.vbs .
        mv -f ./release/run-UI.bat .
        mv -f ./release/run-UI-debug.bat .
        mv -f ./release/uninstall.bat .
        mv -f ./release/update.bat .
        mv -f ./release/config/* ./config/
        mv -f ./release/LICENSE/* ./LICENSE/        
        
        zip AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip ILikeAcFun.jar
        zip -m AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip ./install.vbs
        zip -m AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip ./run-UI.bat
        zip -m AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip ./run-UI-debug.bat
        zip -m AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip ./uninstall.bat
        zip -m AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip ./update.bat
        zip -rm AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip ./config/
        zip -rm AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip ./LICENSE/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: V${{steps.tag_latest.outputs.value}}
        name: AcfunDown - v${{steps.tag_latest.outputs.value}}
        body_path: ./.github/release.info
        draft: false
        prerelease: false
        files: |
          AcfunDown.v${{steps.tag_latest.outputs.value}}.release.zip
          
